[workspace]
resolver = "2"
members = [
    "openehr-model",
]

[workspace.dependencies]
nutype = { version = "0.5.0", features = ["regex", "serde"] }
regex = "1.11.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
paste = "1.0.15"
thiserror = "1.0.68"
