[package]
name = "openehr-model"
version = "0.1.0"
edition = "2021"

[dependencies]
nutype = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
paste = { workspace = true }
